from database import get_session

COMIDAS = [
    {"nombre": "Pizza Margherita", "tipo": "Italiana", "ingredientes": ["harina", "queso mozzarella", "tomate", "albahaca", "aceite de oliva", "sal", "levadura", "agua", "orégano", "ajo", "pimienta", "azúcar"], "imagen": "https://images.unsplash.com/photo-1574126154517-d6e7b1b6f100"},
    {"nombre": "Sushi Nigiri", "tipo": "Japonesa", "ingredientes": ["arroz", "pescado crudo", "alga nori", "soja", "wasabi", "jengibre", "vinagre de arroz", "azúcar", "sal", "sésamo", "cebollino", "limón"], "imagen": "https://images.unsplash.com/photo-1579871494447-9811cf80d66c"},
    {"nombre": "Tacos al Pastor", "tipo": "Mexicana", "ingredientes": ["carne de cerdo", "tortilla de maíz", "cebolla", "cilantro", "piña", "chile", "ajo", "comino", "orégano", "limón", "sal", "pimienta", "vinagre"], "imagen": "https://images.unsplash.com/photo-1565299585323-38d6b0865b47"},
    {"nombre": "Hamburguesa Clásica", "tipo": "Americana", "ingredientes": ["pan de hamburguesa", "carne de res", "queso cheddar", "lechuga", "tomate", "cebolla", "ketchup", "mostaza", "mayonesa", "pepinillos", "sal", "pimienta", "aceite"], "imagen": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd"},
    {"nombre": "Pasta Carbonara", "tipo": "Italiana", "ingredientes": ["espagueti", "queso pecorino", "huevo", "panceta", "pimienta negra", "sal", "ajo", "aceite de oliva", "perejil", "cebolla", "leche", "harina"], "imagen": "https://images.unsplash.com/photo-1608897013039-887f21d8c804"},
    {"nombre": "Ensalada César", "tipo": "Saludable", "ingredientes": ["lechuga romana", "pollo", "queso parmesano", "crutones", "ajo", "limón", "mostaza", "aceite de oliva", "huevo", "anchoas", "pimienta", "sal", "vinagre"], "imagen": "https://images.unsplash.com/photo-1550304943-4f24f54ddde9"},
    {"nombre": "Ramen Shoyu", "tipo": "Japonesa", "ingredientes": ["fideos", "caldo de pollo", "soja", "cerdo", "alga nori", "cebollino", "huevo", "jengibre", "ajo", "sésamo", "aceite", "mirin", "sal"], "imagen": "https://images.unsplash.com/photo-1516108317508-6788f6a160e4"},
    {"nombre": "Ceviche Peruano", "tipo": "Peruana", "ingredientes": ["pescado blanco", "limón", "cebolla morada", "cilantro", "chile", "maíz", "camote", "ajo", "sal", "pimienta", "jengibre", "apio"], "imagen": "https://images.unsplash.com/photo-1535392433074-4818d9d4af38"},
    {"nombre": "Pollo Frito", "tipo": "Americana", "ingredientes": ["pollo", "harina", "huevo", "leche", "pimentón", "ajo en polvo", "cebolla en polvo", "sal", "pimienta", "aceite", "comino", "orégano"], "imagen": "https://images.unsplash.com/photo-1594224457761-12e9a34a8658"},
    {"nombre": "Paella Valenciana", "tipo": "Española", "ingredientes": ["arroz", "pollo", "conejo", "pimiento", "tomate", "azafrán", "caldo de pescado", "judías verdes", "garrofó", "aceite de oliva", "sal", "romero"], "imagen": "https://images.unsplash.com/photo-1532634922-8fe0b757fb13"},
    {"nombre": "Pad Thai", "tipo": "Tailandesa", "ingredientes": ["fideos de arroz", "camarones", "huevo", "cacahuete", "cebollino", "soja", "chile", "limón", "azúcar", "salsa de pescado", "ajo", "aceite", "brotes de soja"], "imagen": "https://images.unsplash.com/photo-1559314808-050d2d7e3594"},
    {"nombre": "Pollo al Curry", "tipo": "India", "ingredientes": ["pollo", "arroz", "leche de coco", "curry", "cebolla", "ajo", "jengibre", "tomate", "cilantro", "comino", "cúrcuma", "pimienta", "sal"], "imagen": "https://images.unsplash.com/photo-1603894584373-2d7c7b1da4e6"},
    {"nombre": "Falafel", "tipo": "Mediterranea", "ingredientes": ["garbanzo", "tahini", "ajo", "cebolla", "perejil", "comino", "cilantro", "harina", "limón", "sal", "pimienta", "aceite"], "imagen": "https://images.unsplash.com/photo-1590759483537-37e9e3293d10"},
    {"nombre": "Empanadas Argentinas", "tipo": "Latinoamericana", "ingredientes": ["harina", "carne de res", "cebolla", "huevo", "aceitunas", "pimentón", "comino", "ajo", "sal", "pimienta", "aceite", "pasas"], "imagen": "https://images.unsplash.com/photo-1626085596355-4a285b7d76ff"},
    {"nombre": "Sopa de Lentejas", "tipo": "Saludable", "ingredientes": ["lentejas", "cebolla", "zanahoria", "tomate", "apio", "ajo", "comino", "laurel", "pimienta", "sal", "aceite de oliva", "caldo de verduras"], "imagen": "https://images.unsplash.com/photo-1543332164-6e82f355badc"},
    {"nombre": "Gyros de Cordero", "tipo": "Griega", "ingredientes": ["cordero", "pan pita", "yogur", "tomate", "cebolla", "lechuga", "ajo", "limón", "orégano", "comino", "sal", "pimienta"], "imagen": "https://images.unsplash.com/photo-1626700051175-9f6a5c3a1d44"},
    {"nombre": "Dim Sum", "tipo": "China", "ingredientes": ["harina", "camarones", "cerdo", "soja", "cebollino", "jengibre", "sésamo", "ajo", "azúcar", "vinagre de arroz", "aceite", "bambú"], "imagen": "https://images.unsplash.com/photo-1541697418240-7a8a8e4b8e7e"},
    {"nombre": "Chiles Rellenos", "tipo": "Mexicana", "ingredientes": ["pimiento", "queso", "carne de res", "tomate", "cebolla", "ajo", "huevo", "harina", "chile", "sal", "pimienta", "aceite"], "imagen": "https://images.unsplash.com/photo-1606856052345-1446d3306b34"},
    {"nombre": "Moussaka", "tipo": "Griega", "ingredientes": ["berenjena", "carne de cordero", "tomate", "queso", "cebolla", "ajo", "harina", "leche", "huevo", "canela", "pimienta", "sal"], "imagen": "https://images.unsplash.com/photo-1598961949636-5c5327b8d5c4"},
    {"nombre": "Biryani de Pollo", "tipo": "India", "ingredientes": ["arroz", "pollo", "yogur", "cebolla", "tomate", "jengibre", "ajo", "cúrcuma", "comino", "cilantro", "chile", "azafrán", "cardamomo"], "imagen": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc"},
    {"nombre": "Poke de Atún", "tipo": "Hawaiana", "ingredientes": ["atún", "arroz", "aguacate", "alga", "soja", "sésamo", "cebollino", "jengibre", "limón", "chile", "azúcar", "vinagre"], "imagen": "https://images.unsplash.com/photo-1580818138587-69a8cef8651b"},
    {"nombre": "Lasaña Boloñesa", "tipo": "Italiana", "ingredientes": ["pasta", "carne de res", "queso mozzarella", "tomate", "cebolla", "ajo", "zanahoria", "apio", "albahaca", "orégano", "leche", "harina"], "imagen": "https://images.unsplash.com/photo-1608897013039-887f21d8c804"},
    {"nombre": "Pho de Res", "tipo": "Vietnamita", "ingredientes": ["fideos de arroz", "caldo de res", "carne de res", "cebollino", "cilantro", "jengibre", "anis estrellado", "canela", "clavo", "soja", "limón", "chile"], "imagen": "https://images.unsplash.com/photo-1542384556-8e6c87d50878"},
    {"nombre": "Arepa Rellena", "tipo": "Latinoamericana", "ingredientes": ["harina de maíz", "queso", "carne mechada", "aguacate", "cebolla", "tomate", "cilantro", "sal", "pimienta", "aceite", "limón"], "imagen": "https://images.unsplash.com/photo-1625220253380-9e75e0aa9364"},
    {"nombre": "Sashimi de Salmón", "tipo": "Japonesa", "ingredientes": ["salmón", "soja", "wasabi", "jengibre", "limón", "cebollino", "sésamo", "arroz", "alga", "vinagre de arroz", "azúcar"], "imagen": "https://images.unsplash.com/photo-1607301405650-0d8b8487da8f"},
    {"nombre": "Couscous con Verduras", "tipo": "Mediterranea", "ingredientes": ["sémola", "calabacín", "zanahoria", "cebolla", "pimiento", "garbanzo", "comino", "cilantro", "limón", "aceite de oliva", "sal", "pimienta"], "imagen": "https://images.unsplash.com/photo-1621510042858-5764d4cd0806"},
    {"nombre": "Tiramisú", "tipo": "Italiana", "ingredientes": ["queso mascarpone", "café", "bizcocho", "cacao", "azúcar", "huevo", "licor de café", "leche", "harina", "vainilla", "sal"], "imagen": "https://images.unsplash.com/photo-1571870763603-8b5bdfd22c26"},
    {"nombre": "Enchiladas Verdes", "tipo": "Mexicana", "ingredientes": ["tortilla de maíz", "pollo", "queso", "salsa verde", "cebolla", "cilantro", "chile", "ajo", "limón", "sal", "pimienta", "aceite"], "imagen": "https://images.unsplash.com/photo-1603641572832-6beb18a0e3bc"},
    {"nombre": "Spring Rolls", "tipo": "China", "ingredientes": ["papel de arroz", "camarones", "lechuga", "zanahoria", "pepino", "cilantro", "soja", "cacahuete", "jengibre", "chile", "azúcar", "limón"], "imagen": "https://images.unsplash.com/photo-1582746408817-7e4a92e8e5e6"},
    {"nombre": "Shawarma de Pollo", "tipo": "Mediterranea", "ingredientes": ["pollo", "pan pita", "tahini", "lechuga", "tomate", "cebolla", "ajo", "limón", "comino", "pimentón", "yogur", "pimienta"], "imagen": "https://images.unsplash.com/photo-1619632675630-23a944860c0b"},
    {"nombre": "Sopa Pho Vegetariana", "tipo": "Vietnamita", "ingredientes": ["fideos de arroz", "caldo de verduras", "tofu", "cebollino", "cilantro", "jengibre", "anis estrellado", "canela", "clavo", "soja", "limón", "chile"], "imagen": "https://images.unsplash.com/photo-1542384556-8e6c87d50878"},
    {"nombre": "Tacos de Pescado", "tipo": "Mexicana", "ingredientes": ["pescado", "tortilla de maíz", "repollo", "salsa de yogur", "limón", "cilantro", "chile", "ajo", "comino", "pimienta", "sal", "aceite"], "imagen": "https://images.unsplash.com/photo-1559748092-7a8f9e9b"},
    {"nombre": "Risotto de Champiñones", "tipo": "Italiana", "ingredientes": ["arroz arborio", "champiñones", "queso parmesano", "caldo de verduras", "cebolla", "ajo", "mantequilla", "vino blanco", "perejil", "sal", "pimienta"], "imagen": "https://images.unsplash.com/photo-1606946313237-7e6c2d"},
    {"nombre": "Butter Chicken", "tipo": "India", "ingredientes": ["pollo", "leche de coco", "tomate", "cebolla", "ajo", "jengibre", "cúrcuma", "comino", "cilantro", "chile", "yogur", "mantequilla"], "imagen": "https://images.unsplash.com/photo-1603894584373-2d7c7b1da4e6"},
    {"nombre": "Hummus con Pita", "tipo": "Mediterranea", "ingredientes": ["garbanzo", "tahini", "limón", "ajo", "aceite de oliva", "comino", "pimentón", "sal", "pimienta", "pan pita", "perejil"], "imagen": "https://images.unsplash.com/photo-1594053165236-7d3b"},
    {"nombre": "Tamales", "tipo": "Mexicana", "ingredientes": ["harina de maíz", "carne de cerdo", "chile", "tomate", "cebolla", "ajo", "comino", "orégano", "sal", "pimienta", "hoja de maíz"], "imagen": "https://images.unsplash.com/photo-1606856052345-1446d3306b34"},
    {"nombre": "Sopa de Miso", "tipo": "Japonesa", "ingredientes": ["miso", "tofu", "alga wakame", "cebollino", "caldo dashi", "soja", "jengibre", "sésamo", "arroz", "sal", "mirin"], "imagen": "https://images.unsplash.com/photo-1580226866482-3d6e2"},
    {"nombre": "Pato Pekín", "tipo": "China", "ingredientes": ["pato", "tortita de arroz", "cebollino", "pepino", "salsa hoisin", "soja", "jengibre", "ajo", "azúcar", "vinagre", "sésamo"], "imagen": "https://images.unsplash.com/photo-1598961949636-5b8a8e4b8e7e"},
    {"nombre": "Baklava", "tipo": "Mediterranea", "ingredientes": ["hojaldre", "nueces", "miel", "azúcar", "canela", "clavo", "limón", "mantequilla", "pistacho", "agua", "vainilla"], "imagen": "https://images.unsplash.com/photo-1580130775562-0"},
    {"nombre": "Feijoada", "tipo": "Brasileña", "ingredientes": ["frijoles negros", "cerdo", "carne de res", "cebolla", "ajo", "laurel", "comino", "pimienta", "arroz", "naranja", "cilantro"], "imagen": "https://images.unsplash.com/photo-1603894584373-2d7c7b1da4e6"},
    {"nombre": "Goulash", "tipo": "Húngara", "ingredientes": ["carne de res", "pimiento", "tomate", "cebolla", "ajo", "pimentón", "comino", "laurel", "caldo de carne", "papas", "zanahoria"], "imagen": "https://images.unsplash.com/photo-1598961949636-5b8a8e4b8e7e"},
    {"nombre": "Sopa Tom Yum", "tipo": "Tailandesa", "ingredientes": ["camarones", "chile", "limón", "hierba limón", "galanga", "hojas de lima", "salsa de pescado", "cilantro", "cebolla", "caldo", "azúcar"], "imagen": "https://images.unsplash.com/photo-1582746408817-7e4a92e8e5e6"},
    {"nombre": "Paella de Mariscos", "tipo": "Española", "ingredientes": ["arroz", "calamares", "camarones", "mejillones", "pimiento", "tomate", "azafrán", "caldo de pescado", "ajo", "cebolla", "limón"], "imagen": "https://images.unsplash.com/photo-1532634922-8fe0b757fb13"},
    {"nombre": "Chow Mein", "tipo": "China", "ingredientes": ["fideos", "pollo", "zanahoria", "pimiento", "cebolla", "soja", "sésamo", "jengibre", "ajo", "aceite", "azúcar"], "imagen": "https://images.unsplash.com/photo-1580226866482-3d6e2"},
    {"nombre": "Rendang de Ternera", "tipo": "Indonesa", "ingredientes": ["carne de res", "leche de coco", "chile", "jengibre", "galanga", "cúrcuma", "lemongrass", "ajo", "cebolla", "comino", "cilantro"], "imagen": "https://images.unsplash.com/photo-1603894584373-2d7c7b1da4e6"},
    {"nombre": "Banh Mi", "tipo": "Vietnamita", "ingredientes": ["pan baguette", "cerdo", "zanahoria", "pepino", "cilantro", "chile", "mayonesa", "soja", "limón", "jengibre", "ajo"], "imagen": "https://images.unsplash.com/photo-1580130775562-0"},
    {"nombre": "Quinoa con Verduras", "tipo": "Saludable", "ingredientes": ["quinoa", "calabacín", "pimiento", "zanahoria", "cebolla", "ajo", "limón", "aceite de oliva", "perejil", "comino", "sal"], "imagen": "https://images.unsplash.com/photo-1621510042858-5764d4cd0806"},
    {"nombre": "Tikka Masala", "tipo": "India", "ingredientes": ["pollo", "yogur", "tomate", "cebolla", "ajo", "jengibre", "cúrcuma", "comino", "cilantro", "chile", "leche de coco"], "imagen": "https://images.unsplash.com/photo-1603894584373-2d7c7b1da4e6"},
    {"nombre": "Carpaccio de Res", "tipo": "Italiana", "ingredientes": ["carne de res", "queso parmesano", "rúcula", "limón", "aceite de oliva", "pimienta", "sal", "alcaparras", "mostaza", "cebolla"], "imagen": "https://images.unsplash.com/photo-1598961949636-5b8a8e4b8e7e"},
    {"nombre": "Causa Limeña", "tipo": "Peruana", "ingredientes": ["papa", "atún", "aguacate", "limón", "cebolla", "chile", "cilantro", "mayonesa", "huevo", "sal", "pimienta"], "imagen": "https://images.unsplash.com/photo-1535392433074-7d3b"},
    {"nombre": "Poutine", "tipo": "Canadiense", "ingredientes": ["papas fritas", "queso en grano", "salsa gravy", "cebolla", "pimienta", "sal", "aceite", "harina", "caldo de carne", "mantequilla"], "imagen": "https://images.unsplash.com/photo-1580130775562-0"}
]

def cargar_comidas():
    with get_session() as session:
        for comida in COMIDAS:
            session.run("""
                MERGE (c:Comida {nombre: $nombre})
                SET c.tipo = $tipo, c.imagen = $imagen
            """, nombre=comida["nombre"], tipo=comida["tipo"], imagen=comida["imagen"])
            for ing in comida["ingredientes"]:
                session.run("""
                    MERGE (i:Ingrediente {nombre: $ing})
                    WITH i
                    MATCH (c:Comida {nombre: $nombre})
                    MERGE (c)-[:TIENE]->(i)
                """, ing=ing, nombre=comida["nombre"])